seo: 
  site_name: Tina's Amazing Blog
  title: Default SEO Title
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design: 
  dark-text_color: 'rgb(60,60,65)'
  medium-text_color: 'rgb(90,90,95)'
  light-text_color: '#FBE9D8'
  featured_color: '#C95F38'
  featured-light_color: '#E3825F'
  dark_color: 'rgb(60,60,65)'
  medium_color: '#ede8e4'
  light_color: '#FBE9D8'
  v-light_color: '#f9f9f9'
  contrast_color: '#9B9B7D'
  contrast-dark_color: '#7A7D65'
